### ISSUE TITLE
Field error order priority

### ISSUE THREAD

**Issue by rodleviton** [Odecee/angular-form-lib#4] opened 2015-09-23 11:31 UTC
Hi Brett

When validating a form with a combination of text inputs, select inputs, checkboxes etc no matter what DOM order they are in the basic text inputs are evaluated first. This is mainly an issue as the duScroll plugin scrolls to the "first" error field. I was also able to reproduce this behaviour on the docs page. Is this something you are aware of?

Cheers
Rod

**Comment by uglow** [comment] 2015-09-23 11:37
Hi Rod,

No I wasn't aware of this. I've used this behaviour on a few different forms and it has worked well in the past. Are you able to point out which form in the docs has the incorrect behaviour?

Thanks,
Brett

**Comment by uglow** [comment] 2015-09-23 23:03
The fieldErrorController's link function is called for all of the `input type=text` elements first, then the `select` and `input type=checkbox` elements on the documentation site. I'm not sure why. Could be to do with differences in the element markup (e.g. maybe the checkbox control is deeper in the DOM hierarchy than a text-box?). Consequently, the link() -> scope.$on('form-submit-attempt'). So if the textboxes register first, they will be notified of the event first.

 Feel free to fork & fix. I won't have a lot of time to look at this for a while.

**Comment by rodleviton** [comment] 2015-09-23 23:27
Thanks Brett sounds like you find the issue - apologies for not including an example of how to reproduce. I will have a look into it.

**Comment by uglow** [comment] 2015-09-27 07:10
I'm working on this now. The problem is due to the mixture of controls... most use `templateUrl`, which forces the directive compilation to be delayed (even if the content is already in the template cache), versus `formInput` which uses `template` - which is NOT asynchronous. This results in all of the `formInput` controls being compiled first, then all of the other controls.

I'm changing the way the focusBehaviour works so that it looks for a sourceIndex property (which I've had to add), to determine which control should actually receive the focus.

**Comment by uglow** [comment] 2015-09-28 05:50
Fixed in 7b580de07edc652b6b025a0d017417efc53b879f

The sourceIndex approach did not work, reverted to making `formInput` use a templateUrl like all of the other controls.

Closing.

**Closed by uglow** 2015-09-28 05:50 UTC

**Comment by rodleviton** [comment] 2015-09-29 03:59
Thanks @uglow !!
